Devices:
    - ProductId: "productId"  # 产品 ID 
      DeviceName: "devicename" # 设备名称
      Psk: "psk" # psk 密钥 
      DeviceVersion: "1.0.0" # 上报的固件版本
    - ProductId: "productid" 
      DeviceName: "devicename"
      Psk: "psk"
      MQTTHost: "127.0.0.1" # 手动指定链接地址，优先级更高,未指定为 "productid.URLsuff"
URLSuff: "iotcloud.tencentdevices.com" # 通用后缀



Actions: # Action 信息
  - ActionId: "test1"
    Params: # 空，无返回
  - ActionId: "test2"  # Action 标识符
    Params:
      - bar: 0 # Action 参数

Events:
  SendInterval: 0s # 每x秒发送一次
  EventInfos:
   - EventId: "status_report" # 事件标识符 ID
     EventType: "info" # 事件类型
     EventParams: # 事件参数
       - status: 0 
         message: "test"  
   - EventId: "low_voltage" 
     EventType: "alert" # 告警
     EventParams: 
       - voltage: 0.2
   - EventId: "hardware_fault" 
     EventType: "fault" # 故障 
     EventParams: 
       - name:  "fault"
         error_code: 1215

OTA:
  DownloadingTime: 10s # 下载时间
  BurningTime: 5s # 烧录时间
